
const theDate = new Date();
export const contacts: any[] = [
  {
    id: 'traceyfrancia12345',
    profilePicture: '/assets/testing-doctors/abhirup-maulik.jpg',
    addInfo: '',
    socketID: 'random',
    lastNames: 'Zracey Francia',
    firstNames: 'Christian',
    specialty: 'Alergía',
    hospitals: [
      {
        name: `Vall d' Hebron`,
        address: '123 main st',
        address2: '2-2',
        phoneNumber: 123456789,
        country: 'España',
        province: 'Barcelona',
        city: 'Barcelona',
        zipCode: 18032,
        directors: ['frank', 'john'],
      },
      {
        name: `Amma Horta`,
        address: '123 main st',
        address2: '2-2',
        phoneNumber: 123456789,
        country: 'España',
        province: 'Barcelona',
        city: 'Barcelona',
        zipCode: 18032,
        directors: ['frank', 'john'],
      },
    ],
    sex: 'Hombre',
    dateOfBirth: theDate.getDate(),
    email: 'testing@test.com',
    country: 'España',
    province: 'Barcelona',
    city: 'Barcelona',
  },
  {
    id: 'janebuxo56789',
    profilePicture: '/assets/testing-doctors/ayesha-chowdhuri.jpg',
    addInfo: 'Lorem Ipsum',
    socketID: 'cnmBu7GXgXSad2j8AAAL',
    lastNames: 'Zane Buxó',
    firstNames: 'Lorena',
    specialty: 'Cirugía',
    hospitals: [
      {
        name: `Creu Blanc`,
        address: '123 main st',
        address2: '2-2',
        phoneNumber: 123456789,
        country: 'España',
        province: 'Barcelona',
        city: 'Barcelona',
        zipCode: 18032,
        directors: ['frank', 'john'],
      },
    ],
    sex: 'Mujer',
    dateOfBirth: theDate.getDate(),
    email: 'this@gmail.com',
    country: 'España',
    province: 'Barcelona',
    city: 'Barcelona',
  },
  {
    id: 'palmamontanez32154',
    profilePicture: '/assets/testing-doctors/about-doctor-img-1.jpg',
    addInfo: 'Lorem Ipsum',
    socketID: 'ASDFASDF234SDF',
    lastNames: 'Palma Montañez',
    firstNames: 'Laura',
    specialty: 'Cirugía Corazon',
    hospitals: [
      {
        name: `Hospital Beraneu`,
        address: '123 main st',
        address2: '2-2',
        phoneNumber: 123456789,
        country: 'España',
        province: 'Barcelona',
        city: 'Madrid',
        zipCode: 48032,
        directors: ['frank', 'john'],
      },
    ],
    sex: 'Mujer',
    dateOfBirth: theDate.getDate(),
    email: '523@gmail.odd',
    country: 'España',
    province: 'Madrid',
    city: 'Madrid',
  },
  {
    id: 'marquesperiera98876',
    profilePicture: '/assets/testing-doctors/default-male.jpg',
    addInfo: 'Lorem Ipsum',
    socketID: 'VgYPRqiJYFxrbAuaAAAA',
    lastNames: 'Marques Periera',
    firstNames: 'Leandro',
    specialty: 'Pediatria Infantil',
    hospitals: [
      {
        name: `Barcelona General`,
        address: '123 main st',
        address2: '2-2',
        phoneNumber: 123456789,
        country: 'España',
        province: 'Barcelona',
        city: 'Barcelona',
        zipCode: 28032,
        directors: ['frank', 'john'],
      },
    ],
    sex: 'Hombre',
    dateOfBirth: theDate.getDate(),
    email: 'adsf@sdg.com',
    country: 'España',
    province: 'Barcelona',
    city: 'Barcelona',
  },
  // {
  //   id: '',
  //   profilePicture: ,
  //   socketID: ,
  //   lastNames: ,
  //   firstNames: ,
  //   specialty: ,
  //   hospitals: [],
  //   sex: ,
  //   dateOfBirth: Date.now(),
  //   email: ,
  //   country: ,
  //   province: ,
  //   city: ,
  // },
];
